# ####################################################################

#  Created by Genus(TM) Synthesis Solution 21.14-s082_1 on Thu Oct 17 11:46:10 CEST 2024

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1fF
set_units -time 1ps

# Set the current design
current_design PROACT_top

create_clock -name "SYSCLK_P" -period 100000.0 -waveform {50000.0 100000.0} [get_ports SYSCLK_P]
group_path -weight 1.000000 -name cg_enable_group_SYSCLK_P -through [list \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_dscratch0_csr/RC_CG_HIER_INST59/enable]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_dscratch0_csr/RC_CG_HIER_INST59/RC_CGIC_INST/E]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_dscratch1_csr/RC_CG_HIER_INST60/enable]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_dscratch1_csr/RC_CG_HIER_INST60/RC_CGIC_INST/E]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_mscratch_csr/RC_CG_HIER_INST61/enable]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_mscratch_csr/RC_CG_HIER_INST61/RC_CGIC_INST/E]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_mtval_csr/RC_CG_HIER_INST62/enable]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_mtval_csr/RC_CG_HIER_INST62/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST0/enable]  \
  [get_pins RC_CG_HIER_INST0/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST2/enable]  \
  [get_pins RC_CG_HIER_INST2/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST3/enable]  \
  [get_pins RC_CG_HIER_INST3/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST4/enable]  \
  [get_pins RC_CG_HIER_INST4/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST5/enable]  \
  [get_pins RC_CG_HIER_INST5/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST7/enable]  \
  [get_pins RC_CG_HIER_INST7/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST8/enable]  \
  [get_pins RC_CG_HIER_INST8/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST9/enable]  \
  [get_pins RC_CG_HIER_INST9/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST10/enable]  \
  [get_pins RC_CG_HIER_INST10/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST11/enable]  \
  [get_pins RC_CG_HIER_INST11/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST12/enable]  \
  [get_pins RC_CG_HIER_INST12/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST13/enable]  \
  [get_pins RC_CG_HIER_INST13/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST14/enable]  \
  [get_pins RC_CG_HIER_INST14/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST15/enable]  \
  [get_pins RC_CG_HIER_INST15/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST16/enable]  \
  [get_pins RC_CG_HIER_INST16/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST17/enable]  \
  [get_pins RC_CG_HIER_INST17/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST18/enable]  \
  [get_pins RC_CG_HIER_INST18/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST19/enable]  \
  [get_pins RC_CG_HIER_INST19/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST20/enable]  \
  [get_pins RC_CG_HIER_INST20/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST21/enable]  \
  [get_pins RC_CG_HIER_INST21/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST22/enable]  \
  [get_pins RC_CG_HIER_INST22/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST23/enable]  \
  [get_pins RC_CG_HIER_INST23/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST24/enable]  \
  [get_pins RC_CG_HIER_INST24/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST25/enable]  \
  [get_pins RC_CG_HIER_INST25/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST26/enable]  \
  [get_pins RC_CG_HIER_INST26/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST27/enable]  \
  [get_pins RC_CG_HIER_INST27/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST28/enable]  \
  [get_pins RC_CG_HIER_INST28/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST29/enable]  \
  [get_pins RC_CG_HIER_INST29/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST30/enable]  \
  [get_pins RC_CG_HIER_INST30/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST31/enable]  \
  [get_pins RC_CG_HIER_INST31/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST32/enable]  \
  [get_pins RC_CG_HIER_INST32/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST33/enable]  \
  [get_pins RC_CG_HIER_INST33/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST34/enable]  \
  [get_pins RC_CG_HIER_INST34/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST35/enable]  \
  [get_pins RC_CG_HIER_INST35/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST36/enable]  \
  [get_pins RC_CG_HIER_INST36/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST37/enable]  \
  [get_pins RC_CG_HIER_INST37/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST38/enable]  \
  [get_pins RC_CG_HIER_INST38/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST39/enable]  \
  [get_pins RC_CG_HIER_INST39/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST40/enable]  \
  [get_pins RC_CG_HIER_INST40/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST41/enable]  \
  [get_pins RC_CG_HIER_INST41/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST42/enable]  \
  [get_pins RC_CG_HIER_INST42/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST43/enable]  \
  [get_pins RC_CG_HIER_INST43/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST44/enable]  \
  [get_pins RC_CG_HIER_INST44/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST45/enable]  \
  [get_pins RC_CG_HIER_INST45/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST46/enable]  \
  [get_pins RC_CG_HIER_INST46/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST47/enable]  \
  [get_pins RC_CG_HIER_INST47/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST48/enable]  \
  [get_pins RC_CG_HIER_INST48/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST49/enable]  \
  [get_pins RC_CG_HIER_INST49/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST50/enable]  \
  [get_pins RC_CG_HIER_INST50/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST51/enable]  \
  [get_pins RC_CG_HIER_INST51/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST52/enable]  \
  [get_pins RC_CG_HIER_INST52/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST53/enable]  \
  [get_pins RC_CG_HIER_INST53/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST55/enable]  \
  [get_pins RC_CG_HIER_INST55/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST56/enable]  \
  [get_pins RC_CG_HIER_INST56/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST57/enable]  \
  [get_pins RC_CG_HIER_INST57/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST58/enable]  \
  [get_pins RC_CG_HIER_INST58/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST0/enable]  \
  [get_pins RC_CG_HIER_INST0/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST2/enable]  \
  [get_pins RC_CG_HIER_INST2/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST3/enable]  \
  [get_pins RC_CG_HIER_INST3/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST4/enable]  \
  [get_pins RC_CG_HIER_INST4/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST5/enable]  \
  [get_pins RC_CG_HIER_INST5/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST7/enable]  \
  [get_pins RC_CG_HIER_INST7/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST8/enable]  \
  [get_pins RC_CG_HIER_INST8/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST9/enable]  \
  [get_pins RC_CG_HIER_INST9/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST10/enable]  \
  [get_pins RC_CG_HIER_INST10/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST11/enable]  \
  [get_pins RC_CG_HIER_INST11/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST12/enable]  \
  [get_pins RC_CG_HIER_INST12/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST13/enable]  \
  [get_pins RC_CG_HIER_INST13/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST14/enable]  \
  [get_pins RC_CG_HIER_INST14/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST15/enable]  \
  [get_pins RC_CG_HIER_INST15/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST16/enable]  \
  [get_pins RC_CG_HIER_INST16/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST17/enable]  \
  [get_pins RC_CG_HIER_INST17/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST18/enable]  \
  [get_pins RC_CG_HIER_INST18/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST19/enable]  \
  [get_pins RC_CG_HIER_INST19/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST20/enable]  \
  [get_pins RC_CG_HIER_INST20/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST21/enable]  \
  [get_pins RC_CG_HIER_INST21/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST22/enable]  \
  [get_pins RC_CG_HIER_INST22/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST23/enable]  \
  [get_pins RC_CG_HIER_INST23/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST24/enable]  \
  [get_pins RC_CG_HIER_INST24/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST25/enable]  \
  [get_pins RC_CG_HIER_INST25/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST26/enable]  \
  [get_pins RC_CG_HIER_INST26/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST27/enable]  \
  [get_pins RC_CG_HIER_INST27/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST28/enable]  \
  [get_pins RC_CG_HIER_INST28/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST29/enable]  \
  [get_pins RC_CG_HIER_INST29/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST30/enable]  \
  [get_pins RC_CG_HIER_INST30/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST31/enable]  \
  [get_pins RC_CG_HIER_INST31/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST32/enable]  \
  [get_pins RC_CG_HIER_INST32/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST33/enable]  \
  [get_pins RC_CG_HIER_INST33/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST34/enable]  \
  [get_pins RC_CG_HIER_INST34/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST35/enable]  \
  [get_pins RC_CG_HIER_INST35/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST36/enable]  \
  [get_pins RC_CG_HIER_INST36/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST37/enable]  \
  [get_pins RC_CG_HIER_INST37/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST38/enable]  \
  [get_pins RC_CG_HIER_INST38/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST39/enable]  \
  [get_pins RC_CG_HIER_INST39/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST40/enable]  \
  [get_pins RC_CG_HIER_INST40/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST41/enable]  \
  [get_pins RC_CG_HIER_INST41/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST42/enable]  \
  [get_pins RC_CG_HIER_INST42/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST43/enable]  \
  [get_pins RC_CG_HIER_INST43/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST44/enable]  \
  [get_pins RC_CG_HIER_INST44/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST45/enable]  \
  [get_pins RC_CG_HIER_INST45/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST46/enable]  \
  [get_pins RC_CG_HIER_INST46/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST47/enable]  \
  [get_pins RC_CG_HIER_INST47/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST48/enable]  \
  [get_pins RC_CG_HIER_INST48/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST49/enable]  \
  [get_pins RC_CG_HIER_INST49/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST50/enable]  \
  [get_pins RC_CG_HIER_INST50/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST51/enable]  \
  [get_pins RC_CG_HIER_INST51/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST52/enable]  \
  [get_pins RC_CG_HIER_INST52/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST53/enable]  \
  [get_pins RC_CG_HIER_INST53/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST55/enable]  \
  [get_pins RC_CG_HIER_INST55/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST56/enable]  \
  [get_pins RC_CG_HIER_INST56/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST57/enable]  \
  [get_pins RC_CG_HIER_INST57/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST58/enable]  \
  [get_pins RC_CG_HIER_INST58/RC_CGIC_INST/E]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_dscratch0_csr/RC_CG_HIER_INST59/enable]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_dscratch0_csr/RC_CG_HIER_INST59/RC_CGIC_INST/E]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_dscratch1_csr/RC_CG_HIER_INST60/enable]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_dscratch1_csr/RC_CG_HIER_INST60/RC_CGIC_INST/E]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_mscratch_csr/RC_CG_HIER_INST61/enable]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_mscratch_csr/RC_CG_HIER_INST61/RC_CGIC_INST/E]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_mtval_csr/RC_CG_HIER_INST62/enable]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_mtval_csr/RC_CG_HIER_INST62/RC_CGIC_INST/E]  \
  [get_pins RC_CG_DECLONE_HIER_INST/RC_CGIC_INST/E]  \
  [get_pins RC_CG_DECLONE_HIER_INST/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST0/enable]  \
  [get_pins RC_CG_HIER_INST0/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST2/enable]  \
  [get_pins RC_CG_HIER_INST2/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST3/enable]  \
  [get_pins RC_CG_HIER_INST3/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST4/enable]  \
  [get_pins RC_CG_HIER_INST4/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST5/enable]  \
  [get_pins RC_CG_HIER_INST5/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST7/enable]  \
  [get_pins RC_CG_HIER_INST7/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST8/enable]  \
  [get_pins RC_CG_HIER_INST8/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST9/enable]  \
  [get_pins RC_CG_HIER_INST9/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST10/enable]  \
  [get_pins RC_CG_HIER_INST10/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST11/enable]  \
  [get_pins RC_CG_HIER_INST11/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST12/enable]  \
  [get_pins RC_CG_HIER_INST12/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST13/enable]  \
  [get_pins RC_CG_HIER_INST13/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST14/enable]  \
  [get_pins RC_CG_HIER_INST14/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST15/enable]  \
  [get_pins RC_CG_HIER_INST15/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST16/enable]  \
  [get_pins RC_CG_HIER_INST16/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST17/enable]  \
  [get_pins RC_CG_HIER_INST17/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST18/enable]  \
  [get_pins RC_CG_HIER_INST18/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST19/enable]  \
  [get_pins RC_CG_HIER_INST19/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST20/enable]  \
  [get_pins RC_CG_HIER_INST20/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST21/enable]  \
  [get_pins RC_CG_HIER_INST21/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST22/enable]  \
  [get_pins RC_CG_HIER_INST22/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST23/enable]  \
  [get_pins RC_CG_HIER_INST23/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST24/enable]  \
  [get_pins RC_CG_HIER_INST24/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST25/enable]  \
  [get_pins RC_CG_HIER_INST25/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST26/enable]  \
  [get_pins RC_CG_HIER_INST26/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST27/enable]  \
  [get_pins RC_CG_HIER_INST27/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST28/enable]  \
  [get_pins RC_CG_HIER_INST28/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST29/enable]  \
  [get_pins RC_CG_HIER_INST29/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST30/enable]  \
  [get_pins RC_CG_HIER_INST30/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST31/enable]  \
  [get_pins RC_CG_HIER_INST31/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST32/enable]  \
  [get_pins RC_CG_HIER_INST32/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST33/enable]  \
  [get_pins RC_CG_HIER_INST33/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST34/enable]  \
  [get_pins RC_CG_HIER_INST34/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST35/enable]  \
  [get_pins RC_CG_HIER_INST35/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST36/enable]  \
  [get_pins RC_CG_HIER_INST36/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST37/enable]  \
  [get_pins RC_CG_HIER_INST37/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST38/enable]  \
  [get_pins RC_CG_HIER_INST38/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST39/enable]  \
  [get_pins RC_CG_HIER_INST39/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST40/enable]  \
  [get_pins RC_CG_HIER_INST40/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST41/enable]  \
  [get_pins RC_CG_HIER_INST41/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST42/enable]  \
  [get_pins RC_CG_HIER_INST42/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST43/enable]  \
  [get_pins RC_CG_HIER_INST43/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST44/enable]  \
  [get_pins RC_CG_HIER_INST44/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST45/enable]  \
  [get_pins RC_CG_HIER_INST45/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST46/enable]  \
  [get_pins RC_CG_HIER_INST46/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST47/enable]  \
  [get_pins RC_CG_HIER_INST47/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST48/enable]  \
  [get_pins RC_CG_HIER_INST48/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST49/enable]  \
  [get_pins RC_CG_HIER_INST49/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST50/enable]  \
  [get_pins RC_CG_HIER_INST50/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST51/enable]  \
  [get_pins RC_CG_HIER_INST51/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST52/enable]  \
  [get_pins RC_CG_HIER_INST52/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST53/enable]  \
  [get_pins RC_CG_HIER_INST53/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST55/enable]  \
  [get_pins RC_CG_HIER_INST55/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST56/enable]  \
  [get_pins RC_CG_HIER_INST56/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST57/enable]  \
  [get_pins RC_CG_HIER_INST57/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST58/enable]  \
  [get_pins RC_CG_HIER_INST58/RC_CGIC_INST/E]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_dscratch0_csr/RC_CG_HIER_INST59/enable]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_dscratch0_csr/RC_CG_HIER_INST59/RC_CGIC_INST/E]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_dscratch1_csr/RC_CG_HIER_INST60/enable]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_dscratch1_csr/RC_CG_HIER_INST60/RC_CGIC_INST/E]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_mscratch_csr/RC_CG_HIER_INST61/enable]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_mscratch_csr/RC_CG_HIER_INST61/RC_CGIC_INST/E]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_mtval_csr/RC_CG_HIER_INST62/enable]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_mtval_csr/RC_CG_HIER_INST62/RC_CGIC_INST/E]  \
  [get_pins RC_CG_DECLONE_HIER_INST/enable]  \
  [get_pins RC_CG_DECLONE_HIER_INST/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST0/enable]  \
  [get_pins RC_CG_HIER_INST0/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST2/enable]  \
  [get_pins RC_CG_HIER_INST2/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST3/enable]  \
  [get_pins RC_CG_HIER_INST3/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST4/enable]  \
  [get_pins RC_CG_HIER_INST4/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST5/enable]  \
  [get_pins RC_CG_HIER_INST5/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST7/enable]  \
  [get_pins RC_CG_HIER_INST7/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST8/enable]  \
  [get_pins RC_CG_HIER_INST8/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST9/enable]  \
  [get_pins RC_CG_HIER_INST9/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST10/enable]  \
  [get_pins RC_CG_HIER_INST10/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST11/enable]  \
  [get_pins RC_CG_HIER_INST11/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST12/enable]  \
  [get_pins RC_CG_HIER_INST12/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST13/enable]  \
  [get_pins RC_CG_HIER_INST13/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST14/enable]  \
  [get_pins RC_CG_HIER_INST14/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST15/enable]  \
  [get_pins RC_CG_HIER_INST15/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST16/enable]  \
  [get_pins RC_CG_HIER_INST16/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST17/enable]  \
  [get_pins RC_CG_HIER_INST17/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST18/enable]  \
  [get_pins RC_CG_HIER_INST18/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST19/enable]  \
  [get_pins RC_CG_HIER_INST19/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST20/enable]  \
  [get_pins RC_CG_HIER_INST20/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST21/enable]  \
  [get_pins RC_CG_HIER_INST21/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST22/enable]  \
  [get_pins RC_CG_HIER_INST22/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST23/enable]  \
  [get_pins RC_CG_HIER_INST23/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST24/enable]  \
  [get_pins RC_CG_HIER_INST24/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST25/enable]  \
  [get_pins RC_CG_HIER_INST25/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST26/enable]  \
  [get_pins RC_CG_HIER_INST26/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST27/enable]  \
  [get_pins RC_CG_HIER_INST27/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST28/enable]  \
  [get_pins RC_CG_HIER_INST28/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST29/enable]  \
  [get_pins RC_CG_HIER_INST29/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST30/enable]  \
  [get_pins RC_CG_HIER_INST30/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST31/enable]  \
  [get_pins RC_CG_HIER_INST31/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST32/enable]  \
  [get_pins RC_CG_HIER_INST32/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST33/enable]  \
  [get_pins RC_CG_HIER_INST33/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST34/enable]  \
  [get_pins RC_CG_HIER_INST34/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST35/enable]  \
  [get_pins RC_CG_HIER_INST35/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST36/enable]  \
  [get_pins RC_CG_HIER_INST36/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST37/enable]  \
  [get_pins RC_CG_HIER_INST37/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST38/enable]  \
  [get_pins RC_CG_HIER_INST38/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST39/enable]  \
  [get_pins RC_CG_HIER_INST39/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST40/enable]  \
  [get_pins RC_CG_HIER_INST40/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST41/enable]  \
  [get_pins RC_CG_HIER_INST41/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST42/enable]  \
  [get_pins RC_CG_HIER_INST42/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST43/enable]  \
  [get_pins RC_CG_HIER_INST43/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST44/enable]  \
  [get_pins RC_CG_HIER_INST44/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST45/enable]  \
  [get_pins RC_CG_HIER_INST45/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST46/enable]  \
  [get_pins RC_CG_HIER_INST46/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST47/enable]  \
  [get_pins RC_CG_HIER_INST47/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST48/enable]  \
  [get_pins RC_CG_HIER_INST48/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST49/enable]  \
  [get_pins RC_CG_HIER_INST49/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST50/enable]  \
  [get_pins RC_CG_HIER_INST50/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST51/enable]  \
  [get_pins RC_CG_HIER_INST51/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST52/enable]  \
  [get_pins RC_CG_HIER_INST52/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST53/enable]  \
  [get_pins RC_CG_HIER_INST53/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST55/enable]  \
  [get_pins RC_CG_HIER_INST55/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST56/enable]  \
  [get_pins RC_CG_HIER_INST56/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST57/enable]  \
  [get_pins RC_CG_HIER_INST57/RC_CGIC_INST/E]  \
  [get_pins RC_CG_HIER_INST58/enable]  \
  [get_pins RC_CG_HIER_INST58/RC_CGIC_INST/E]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_dscratch0_csr/RC_CG_HIER_INST59/enable]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_dscratch0_csr/RC_CG_HIER_INST59/RC_CGIC_INST/E]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_dscratch1_csr/RC_CG_HIER_INST60/enable]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_dscratch1_csr/RC_CG_HIER_INST60/RC_CGIC_INST/E]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_mscratch_csr/RC_CG_HIER_INST61/enable]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_mscratch_csr/RC_CG_HIER_INST61/RC_CGIC_INST/E]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_mtval_csr/RC_CG_HIER_INST62/enable]  \
  [get_pins u_top_u_ibex_core_cs_registers_i_u_mtval_csr/RC_CG_HIER_INST62/RC_CGIC_INST/E]  \
  [get_pins RC_CG_DECLONE_HIER_INST/enable]  \
  [get_pins RC_CG_DECLONE_HIER_INST/RC_CGIC_INST/E] ]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks SYSCLK_P] -add_delay 2000.0 [get_ports rst]
set_wire_load_mode "enclosed"
